### PR TITLE
Fix lifetime issues

### LINKED ISSUE #57: Multiple lifetime issues
The following state machine generates incorrect code:

```rust
pub struct X;
pub struct Y;

smlang::statemachine! {
    transitions: {
        *State1 + Event1(&'a X) [guard1] / action1 = State2(&'a X),
        State2(&'a X) + Event2(&'b Y) [guard2] / action2 = State3((&'a X, &'b Y)),
    }
}
```

What is generated:

```rust
pub trait StateMachineContext {
    fn guard1<'a>(&mut self, event_data: &'a X) -> Result<(), ()>;
    fn guard2<'b>(&mut self, state_data: &&'a X, event_data: &'b Y) -> Result<(), ()>;
    fn action1<'a, 'a>(&mut self, event_data: &'a X) -> &'a X;
    fn action2<'b>(&mut self, state_data: &'a X, event_data: &'b Y) -> (&'a X, &'b Y);
}

pub enum States<'a> {
    State1,
    State2(&'a X),
    State3((&'a X, &'b Y)),
}

impl<'a> PartialEq for States<'a> {
    // ...
}

pub struct StateMachine<'a, T: StateMachineContext> {
    state: Option<States<'a>>,
    context: T,
}

impl<'a, T: StateMachineContext> StateMachine<'a, T> {
    // ...
    pub const fn new_with_state(context: T, initial_state: States<'a>) -> Self {
        // ...
    }

    pub fn state(&self) -> Result<&States, Error> {
        self.state.as_ref().ok_or_else(|| Error::Poisoned)
    }
 
    pub fn process_event(&mut self, mut event: Events) -> Result<&States, Error> {
        // ...
    }
    // ...
}
```

What is expected to be generated:

```rust
pub trait StateMachineContext {
    fn guard1<'a>(&mut self, event_data: &'a X) -> Result<(), ()>;
    fn guard2<'a, 'b>(&mut self, state_data: &'a X, event_data: &'b Y) -> Result<(), ()>;
    fn action1<'a>(&mut self, event_data: &'a X) -> &'a X;
    fn action2<'a, 'b>(&mut self, state_data: &'a X, event_data: &'b Y) -> (&'a X, &'b Y);
}

pub enum States<'a, 'b> {
    State1,
    State2(&'a X),
    State3((&'a X, &'b Y)),
}

impl<'a, 'b> PartialEq for States<'a, 'b> {
    // ...
}

pub struct StateMachine<'a, 'b, T: StateMachineContext> {
    state: Option<States<'a, 'b>>,
    context: T,
}

impl<'a, 'b, T: StateMachineContext> StateMachine<'a, 'b, T> {
    // ...
    pub const fn new_with_state(context: T, initial_state: States<'a, 'b>) -> Self {
        // ...
    }
    
    pub fn state(&self) -> Result<&States<'a, 'b>, Error> {
        self.state.as_ref().ok_or_else(|| Error::Poisoned)
    }
 
    pub fn process_event(&mut self, mut event: Events<'a, 'b>) -> Result<&States<'a, 'b>, Error> {
        // ...
    }
    // ...
}
```

### PR DESCRIPTION
**Pull request by oblique**
Fixes #57

### CODE REVIEW

**Comment by oblique** [comment]
For now this fixes #57, but I want to see if there are any other improvements that need to be done to helps as avoid any future mistakes.

**Comment by oblique** [comment]
Ok it is ready for review

**Comment by oblique** [comment]
@ryan-summers ping

File: tests/test.rs [hunk 1]
```diff
@@ -28,3 +28,50 @@ fn wildcard_after_input_state() {
     sm.process_event(Events::Event1).unwrap();
     assert!(matches!(sm.state(), Ok(&States::Fault)));
 }
+
+#[test]
+fn issue_57() {
```
Comment (ryan-summers) [inline tests/test.rs:33]:
```suggestion
fn multiple_lifetimes() {
```

File: macros/src/codegen.rs [hunk 2]
```diff
@@ -279,7 +260,7 @@ pub fn generate_code(sm: &ParsedStateMachine) -> proc_macro2::TokenStream {
                     guard_set.push(guard.clone());
                     guard_list.extend(quote! {
                         #[allow(missing_docs)]
-                        fn #guard_with_lifetimes(&mut self, #temporary_context #state_data #event_data) -> Result<(), #guard_error>;
+                        fn #guard <#all_lifetimes_code> (&mut self, #temporary_context #state_data #event_data) -> Result<(), #guard_error>;
```
Comment (ryan-summers) [inline macros/src/codegen.rs:263]: Is this and below going to generate warnings about unused lifetime specifiers?

File: macros/src/parser/lifetimes.rs [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+    }
+
+    pub fn to_code(&self) -> proc_macro2::TokenStream {
+        if self.is_empty() {
+            quote! {}
+        } else {
+            let lifetimes = &self.0;
+            quote! { #(#lifetimes),* ,}
+        }
+    }
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:46]: I think we should keep anything related to codegen in `codegen.rs`

File: macros/src/parser/lifetimes.rs [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+impl Deref for Lifetimes {
+    type Target = [Lifetime];
+
+    fn deref(&self) -> &[Lifetime] {
+        &self.0[..]
+    }
+}
+
+// helper function for extracting lifetimes from a Type
+fn get_lifetimes(data_type: &Type, lifetimes: &mut Lifetimes) -> Result<(), parse::Error> {
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:64]: Can we just put this in the function above? I don't see a reason to have this live outside of that function.

File: macros/src/parser/lifetimes.rs [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+            }
+            Ok(())
+        }
+        Type::Tuple(tuple) => {
+            for elem in tuple.elems.iter() {
+                get_lifetimes(elem, lifetimes)?;
+            }
+            Ok(())
+        }
+        _ => Ok(()),
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:96]: For all these branches, just let them return nothing and then at the end add a single `Ok()` on the final line of the function.

File: macros/src/parser/lifetimes.rs [hunk 6]
```diff
@@ -0,0 +1,98 @@
+use quote::quote;
+use std::ops::Deref;
+use syn::{parse, spanned::Spanned, GenericArgument, Lifetime, PathArguments, Type};
+
+#[derive(Debug, Clone)]
+pub struct Lifetimes(Vec<Lifetime>);
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:6]: Can we make this a named struct instead of a tuple? The .0.<xxx> syntax is really opaque in my experience and makes it difficult to add functionality later on.

File: macros/src/parser/lifetimes.rs [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+        if self.is_empty() {
+            quote! {}
+        } else {
+            let lifetimes = &self.0;
+            quote! { #(#lifetimes),* ,}
+        }
+    }
+}
+
+impl Default for Lifetimes {
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:49]: Can't we just derive this?

File: macros/src/parser/lifetimes.rs [hunk 8]
```diff
@@ -0,0 +1,98 @@
...
+    }
+}
+
+impl Deref for Lifetimes {
+    type Target = [Lifetime];
+
+    fn deref(&self) -> &[Lifetime] {
+        &self.0[..]
+    }
+}
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:61]: Why do we need `Deref`? Seems somewhat opaque to me

File: macros/src/parser/lifetimes.rs [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+
+    pub fn append(&mut self, lifetimes: &Lifetimes) {
+        for lifetime in lifetimes.0.iter() {
+            self.push(lifetime);
+        }
+    }
+
+    pub fn remove(&mut self, lifetimes: &Lifetimes) {
+        self.0.retain(|lt| !lifetimes.0.contains(lt));
+    }
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:33]: I think this is just https://doc.rust-lang.org/std/ops/trait.Sub.html?

File: macros/src/parser/lifetimes.rs [hunk 10]
```diff
@@ -0,0 +1,98 @@
...
+        let mut lifetimes = Lifetimes::new();
+        get_lifetimes(data_type, &mut lifetimes)?;
+        Ok(lifetimes)
+    }
+
+    pub fn push(&mut self, lifetime: &Lifetime) {
+        if !self.0.contains(lifetime) {
+            self.0.push(lifetime.to_owned());
+        }
+    }
```
Comment (ryan-summers) [inline macros/src/parser/lifetimes.rs:23]: `push()` generally isn't used as a conditional. Perhaps some other nomenclature would help to indicate that the item will only be added if it doesn't already exist, e.g. add_unique?

**Review by ryan-summers — COMMENTED** [review]
I don't have any functional concerns with the changes, just some architectural comments

File: macros/src/codegen.rs (hunk 2 above)
Comment (oblique) [reply macros/src/codegen.rs:263]: No. This is how it is also used on `Events` and `States` definition.

File: macros/src/parser/lifetimes.rs (hunk 3 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs:46]: Ok. Do you prefer a helper (`lifetimes_to_code`) or an `impl Liffetimes` with a single `to_code` method inside?

File: macros/src/parser/lifetimes.rs (hunk 4 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs:64]: `get_lifetimes` is recursive for tuples, that is why i left it split.

File: macros/src/parser/lifetimes.rs (hunk 8 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs]: When `to_code` is under `lifetimes.rs`, we do not need it. But if I move it to `codegen.rs` we will need a way to get access to `&[Lifetime]`. I can remove it and add `to_slice` method if you prefer.

File: macros/src/parser/lifetimes.rs (hunk 9 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs]: `Sub` is not implemented for `Vec`

Comment (oblique) [reply macros/src/parser/lifetimes.rs]: Ah, do you mean I could implement `Sub` for `Lifetimes`?

File: macros/src/parser/lifetimes.rs (hunk 10 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs]: Or maybe `insert`?

File: macros/src/parser/lifetimes.rs (hunk 3 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs]: I thought a better way. I added `impl Tokens for Lifetimes` in `codegen.rs`

File: macros/src/parser/lifetimes.rs (hunk 10 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs]: I renamed `push` to `insert` and `append` to `extend`. If you prefer something else, let me know.

File: macros/src/parser/lifetimes.rs (hunk 9 above)
Comment (oblique) [reply macros/src/parser/lifetimes.rs]: I replaced `remove` with `Sub`

**Comment by oblique** [comment]
All comments resolved. Please review again.

File: macros/src/codegen.rs [hunk 11]
```diff
@@ -572,3 +534,14 @@ pub fn generate_code(sm: &ParsedStateMachine) -> proc_macro2::TokenStream {
...
+impl ToTokens for Lifetimes {
+    fn to_tokens(&self, tokens: &mut TokenStream) {
+        if self.is_empty() {
+            return;
+        }
+
+        let lifetimes = self.as_slice();
+        tokens.extend(quote! { #(#lifetimes),* ,});
+    }
+}
```
Comment (ryan-summers) [inline macros/src/codegen.rs:547]: This should go into the `lifetime.rs` file if it's an explicit impl on that type to keep relevant code together IMO. Sorry for the mixed messaging.

File: macros/src/parser/lifetimes.rs (hunk 4 above)
Comment (ryan-summers) [reply macros/src/parser/lifetimes.rs:77]: Recursion or not shouldn't really impact whether this is a member func of `Lifetimes`. It seems like this is only called with a `&mut Lifetimes` object, so why not make it a member func that takes `&mut self`?

Comment (oblique) [reply macros/src/parser/lifetimes.rs]: Done! I also renamed it to `insert_from_type`

**Review by ryan-summers — APPROVED** [review]
Beautiful, thanks!
